server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.webmanifest$ {
        add_header Cache-Control "no-store";
        default_type application/manifest+json;
    }

    location = /sw.js {
        add_header Cache-Control "no-cache";
    }

    location = /downloads/modern-tribes.apk {
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment; filename="modern-tribes.apk"';
        add_header Cache-Control "no-store";
    }
}