export type IconName =
  | 'plus'
  | 'trash'
  | 'pencil'
  | 'eye'
  | 'arrow-left'
  | 'arrow-right'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevrons-up'
  | 'chevrons-down'
  | 'check'
  | 'x'
  | 'upload'
  | 'download'
  | 'save'
  | 'search'
  | 'user'
  | 'logout'
  | 'refresh'
  | 'settings'
  | 'archive'
  | 'file-text'
  | 'warning'
  | 'info'
  | 'arrow-up'
  | 'arrow-down'
  | 'hash'
  | 'eye-off'
  | 'external-link'
  | 'bell'
  | 'more-vertical'
  | 'palette'
  | 'calendar'
  | 'star'
  | 'bookmark'
  | 'heart'
  | 'home'
  | 'folder'
  | 'list'
  | 'clock'
  | 'map-pin'
  | 'mail'
  | 'tag'
  | 'flag'
  | 'book'
  | 'users'
  | 'message-circle'
  | 'image'
  | 'link'
  | 'lock'
  | 'unlock'
  | 'share-2'
  | 'filter'
  | 'layers'
  | 'target'
  | 'thumbs-up'
  | 'globe'
  | 'sun'
  | 'moon'
  | 'smile'
  | 'help-circle'
  | 'clipboard'
  | 'check-circle'
  | 'alert-circle'
  | 'music'
  | 'video'
  | 'camera'
  | 'briefcase'
  | 'shopping-cart'
  | 'credit-card'
  | 'gift'
  | 'award'
  | 'zap'
  | 'activity'
  | 'grid'
  | 'layout'
  | 'printer'
  | 'phone'
  | 'copy'
  | 'rotate-cw'
  | 'dollar-sign'
  | 'database'
  | 'server'
  | 'cloud'
  | 'coffee'
  | 'headphones'
  | 'mic'
  | 'volume-2'
  | 'disc'
  | 'dumbbell'
  | 'ball'
  | 'watch'
  | 'trending-up'
  | 'compass'
  | 'shield'
  | 'columns'
  | 'check-square'
  | 'file';

export const ICON_NAMES: IconName[] = [
  'plus', 'trash', 'pencil', 'eye', 'arrow-left', 'arrow-right',
  'chevron-up', 'chevron-down', 'chevrons-up', 'chevrons-down',
  'check', 'x', 'upload', 'download', 'save', 'search', 'user',
  'logout', 'refresh', 'settings', 'archive', 'file-text', 'warning',
  'info', 'arrow-up', 'arrow-down', 'hash', 'eye-off', 'external-link',
  'bell', 'more-vertical', 'palette', 'calendar',
  'star', 'bookmark', 'heart', 'home', 'folder', 'list', 'clock',
  'map-pin', 'mail', 'tag', 'flag', 'book', 'users', 'message-circle',
  'image', 'link', 'lock', 'unlock', 'share-2', 'filter', 'layers',
  'target', 'thumbs-up', 'globe', 'sun', 'moon', 'smile', 'help-circle',
  'clipboard', 'check-circle', 'alert-circle', 'music', 'video',
  'camera', 'briefcase', 'shopping-cart', 'credit-card', 'gift',
  'award', 'zap', 'activity', 'grid', 'layout', 'printer', 'phone',
  'copy', 'rotate-cw', 'dollar-sign', 'database', 'server', 'cloud',
  'coffee', 'headphones', 'mic', 'volume-2', 'disc', 'dumbbell', 'ball',
  'watch', 'trending-up', 'compass', 'shield', 'columns', 'check-square',
  'file',
];
